---
# by default use the latest release in the stable channel
k3s_channel: stable

# if no version is specified, and unable obtain a version from the specified release channel, use this version
k3s_fallback_version: v1.18.9+k3s1

# where the k3s binary should be installed...
k3s_bin_dir: /usr/local/bin
# ... and the file permissions that should be used
k3s_bin_owner: root
k3s_bin_group: root
k3s_bin_mode: u=rwx,go=rx

# by default don't replace the k3s binary if already present
# i.e. don't upgrade k3s
k3s_allow_replace_bin: false
